### ISSUE TITLE
Hook for camera registration to obtain id

### ISSUE THREAD

**Issue by jcmaslan** [tnc-ca-geo/video-importer#3]
As we parse and detect camera names like `C2` in issue #2, provide a hook for camera registration that accepts `camera_name`, `user_id`, `access_token`.

For example, the hook might look like:
```
PUT /api/cameras/registered
```
with a configurable payload like:
```json
{
  "camera_name": "C2",
  "user_id": "12345678",
  "access_token": "2qz1th"
}
```
The `camera_id` is an opaque unique value that can be used in subsequent POSTs of video for segmentation and labeling.

**Comment by jhallard** [comment]
This is done and already merged, the video-importer, when it detects a new camera name (using the supplied `--regex` to parse the camera name from the video files) it will call the `register_camera` function defined in the `--hook_module` that is passed in to the importer with the camera name as an argument. The `register_camera` function is supposed to return an ID for that camera as known by the service that it is registered with. 

Can we close this now? @jcmaslan

**Comment by jcmaslan** [comment]
yes
